### ISSUE TITLE
[BUG] Reason for kick/ban bug with nick with special characters

### ISSUE THREAD

**Issue by crashzk** [phara1/advanced-ff-cs2#6]
Plugin applied a kick due to friendly fire, but the kick was for the wrong reason because it read the nick of the player who used friendly fire.

```
css_kick Pa2 死 "Friendly fire warning [2/3]"`
```

死 would be the nickname of the player who committed friendly fire.

**Comment by phara1** [comment]
This should be fixed by using "{Player}" in config

so
> css_slay "{Player}" "reason"

**Comment by crashzk** [comment]
@phara1 I'll test it, but I believe it will give an error, since the key starts with " and ends with " so it can read the command.

```
// This configuration was automatically generated by CounterStrikeSharp for plugin 'advanced_friendlyfire', at 2024/09/27 08:43:53
{
  "Enable/Disable Advanced Friendly Fire": true,
  "Enable/Disable Punishments": true,
  "Damage Inflictors": [
    "inferno",
    "hegrenade_projectile",
    "flashbang_projectile",
    "smokegrenade_projectile",
    "decoy_projectile",
    "planted_c4"
  ],
  "Warning #1 Required Team Damage (HP Metrics)": 150,
  "Warning #1 Chat message": "Evite fogo amigo, ou você será punido! Aviso de fogo amigo [1/3]",
  "Warning #1 Punishment": "css_psay {Player} \u0022Aviso de fogo amigo [1/3]\u0022",
  "Warning #2 Required Team Damage (HP Metrics)": 300,
  "Warning #2 Chat message": "Você foi kickado por causar dano excessivo aos seus companheiros de equipe!",
  "Warning #2 Punishment": "css_kick {Player} \u0022Aviso de fogo amigo [2/3]\u0022",
  "Warning #3 Required Team Damage (HP Metrics)": 500,
  "Warning #3 Chat message": "Você foi banido por causar dano excessivo aos seus companheiros de equipe!",
  "Warning #3 Punishment": "css_ban {Player} 30 \u0022Aviso de fogo amigo [3/3]\u0022",
  "ConfigVersion": 1
}
```
As you can see **Punishemente** needs to open and close `""` for the .json file to read it.

**Comment by phara1** [comment]
> @phara1 I'll test it, but I believe it will give an error, since the key starts with " and ends with " so it can read the command.
> 
> ```
> // This configuration was automatically generated by CounterStrikeSharp for plugin 'advanced_friendlyfire', at 2024/09/27 08:43:53
> {
>   "Enable/Disable Advanced Friendly Fire": true,
>   "Enable/Disable Punishments": true,
>   "Damage Inflictors": [
>     "inferno",
>     "hegrenade_projectile",
>     "flashbang_projectile",
>     "smokegrenade_projectile",
>     "decoy_projectile",
>     "planted_c4"
>   ],
>   "Warning #1 Required Team Damage (HP Metrics)": 150,
>   "Warning #1 Chat message": "Evite fogo amigo, ou você será punido! Aviso de fogo amigo [1/3]",
>   "Warning #1 Punishment": "css_psay {Player} \u0022Aviso de fogo amigo [1/3]\u0022",
>   "Warning #2 Required Team Damage (HP Metrics)": 300,
>   "Warning #2 Chat message": "Você foi kickado por causar dano excessivo aos seus companheiros de equipe!",
>   "Warning #2 Punishment": "css_kick {Player} \u0022Aviso de fogo amigo [2/3]\u0022",
>   "Warning #3 Required Team Damage (HP Metrics)": 500,
>   "Warning #3 Chat message": "Você foi banido por causar dano excessivo aos seus companheiros de equipe!",
>   "Warning #3 Punishment": "css_ban {Player} 30 \u0022Aviso de fogo amigo [3/3]\u0022",
>   "ConfigVersion": 1
> }
> ```
> 
> As you can see **Punishemente** needs to open and close `""` for the **`.json`** file to read it.

>{
>  "Warning #1 Punishment": "css_psay \"{Player}\" \"Aviso de fogo amigo [1/3]\""
>}

Add \" instead of "

**Comment by phara1** [comment]
Fixed
https://github.com/phara1/advanced-ff-cs2/releases/tag/v1.1.3
